query allPtPromises {
    allPtPromises @client {
        id
        title
        context
        content
        createdAt
        lifetime
        location {
             city
             country
        }
    }
}